### ISSUE TITLE
Value of cfg.locref_loss_weight

### ISSUE THREAD

**Issue by Doch88** [mihaifieraru/human-pose-refiner#3]
Hi, is it possible to have the value of 'cfg.locref_loss_weight' that you have used in the training?

I see that this value is not set in your default configuration file (or in the pose_cfg.yaml files), while the repository linked in the README suggests using a value of 0.05. Is this the value that you used?

**Comment by mihaifieraru** [comment]
hi! yes, I've used  locref_loss_weight = 0.05
